package com.bnta.capstone.models;

public enum JobTitle {
    SOFTWARE_ENGINEER,
    PRODUCT_MANAGER,
    DATA_SCIENTIST,
    OPERATIONS_MANAGER,
    CUSTOMER_SERVICE_ASSOCIATE,
    FINANCE_ANALYST,
    MARKETING_MANAGER,
    WAREHOUSE_ASSOCIATE,
    HR_SPECIALIST,
    SOLUTIONS_ARCHITECT,
    LAWYER,



}
